version: '3'
services:
  merger:
    image: merger:latest
    ports:
        - "7777:7777/tcp"
    build:
      context: ./merger
      dockerfile: Dockerfile
    environment:
      - LOGGER_SVC_URL="0.0.0.0:7778"

  logger:
    image: logger:latest
    ports:
      - "7778:7778/tcp"
    build:
      context: ./logger
      dockerfile: Dockerfile
    

